import puppeteer from "puppeteer";
import logger from "../logger.js";

// ---------------------------------------------------------------------------
// PDF Attachment Generator
// ---------------------------------------------------------------------------
// Takes HTML content → launches headless Chrome → generates PDF buffer.
// Uses the same design language as agent emails for visual consistency.
// ---------------------------------------------------------------------------

export interface PDFOptions {
  title: string;
  content: string;
  agentName: string;
  clientBusinessName: string;
  generatedAt?: Date;
}

/**
 * Generate a PDF buffer from structured content.
 * Returns a Buffer ready for email attachment.
 */
export async function generatePDF(options: PDFOptions): Promise<Buffer> {
  const { title, content, agentName, clientBusinessName, generatedAt = new Date() } = options;
  const dateStr = generatedAt.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const contentHtml = content
    .split("\n")
    .filter(Boolean)
    .map((line) => {
      if (line.startsWith("## ")) return `<h2>${line.slice(3)}</h2>`;
      if (line.startsWith("### ")) return `<h3>${line.slice(4)}</h3>`;
      if (line.startsWith("- ") || line.startsWith("• ")) return `<li>${line.slice(2)}</li>`;
      if (line.startsWith("| ")) return line; // table rows handled separately
      return `<p>${line}</p>`;
    })
    .join("\n")
    // Wrap consecutive <li> in <ul>
    .replace(/(<li>.*?<\/li>\n?)+/g, (match) => `<ul>${match}</ul>`);

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      color: #1a1a1a;
      line-height: 1.6;
      padding: 60px;
    }
    .header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      margin-bottom: 40px;
      padding-bottom: 24px;
      border-bottom: 2px solid #1a1a1a;
    }
    .logo {
      width: 40px;
      height: 40px;
      background: #1a1a1a;
      border-radius: 10px;
      color: white;
      display: flex;
      align-items: center;
      justify-content: center;
      font-weight: 700;
      font-size: 18px;
    }
    .header-right {
      text-align: right;
      font-size: 12px;
      color: #6b7280;
    }
    .title {
      font-size: 24px;
      font-weight: 700;
      margin-bottom: 8px;
    }
    .subtitle {
      font-size: 14px;
      color: #6b7280;
      margin-bottom: 32px;
    }
    h2 {
      font-size: 18px;
      font-weight: 600;
      margin: 28px 0 12px 0;
      color: #1a1a1a;
    }
    h3 {
      font-size: 15px;
      font-weight: 600;
      margin: 20px 0 8px 0;
      color: #374151;
    }
    p {
      font-size: 14px;
      margin-bottom: 12px;
      color: #374151;
    }
    ul {
      padding-left: 20px;
      margin-bottom: 16px;
    }
    li {
      font-size: 14px;
      margin-bottom: 6px;
      color: #374151;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 16px 0;
      font-size: 13px;
    }
    th, td {
      padding: 10px 12px;
      text-align: left;
      border-bottom: 1px solid #e5e7eb;
    }
    th {
      background: #f9fafb;
      font-weight: 600;
      color: #1a1a1a;
    }
    .footer {
      margin-top: 48px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      font-size: 11px;
      color: #9ca3af;
    }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="logo">A</div>
    </div>
    <div class="header-right">
      <div>${agentName} · Ambitt Agents</div>
      <div>${clientBusinessName}</div>
      <div>${dateStr}</div>
    </div>
  </div>

  <div class="title">${title}</div>
  <div class="subtitle">Prepared by ${agentName} for ${clientBusinessName}</div>

  <div class="content">
    ${contentHtml}
  </div>

  <div class="footer">
    Generated by ${agentName} at Ambitt Agents · ${dateStr} · ambitt.agency
  </div>
</body>
</html>`;

  let browser;
  try {
    browser = await puppeteer.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });
    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "0", bottom: "0", left: "0", right: "0" },
    });
    return Buffer.from(pdfBuffer);
  } catch (error) {
    logger.error("PDF generation failed", { error, title });
    throw error;
  } finally {
    if (browser) await browser.close();
  }
}
