import prisma from "@/lib/db";

/**
 * Hosted proposal page. The Prospect's `presentationHtml` is a complete HTML
 * document (doctype + head + body) generated by the Handlebars template, so
 * we return it raw via a route handler — no Next chrome, no nested-html issues.
 *
 * Why a route handler instead of a page.tsx: a Next page can't return another
 * full HTML document without nesting `<html>` inside `<html>`. Raw response =
 * pixel-perfect, exactly what the Handlebars renders.
 *
 * Token gates access. The URL token is the auth (no Supabase). Middleware
 * bypasses `/proposals/*` so it's reachable to prospects.
 */
export const dynamic = "force-dynamic";

export async function GET(
  _req: Request,
  ctx: RouteContext<"/proposals/[token]">
) {
  const { token } = await ctx.params;

  const prospect = await prisma.prospect.findUnique({
    where: { token },
    select: { presentationHtml: true, status: true, businessName: true, contactName: true },
  });

  if (!prospect) {
    return new Response(simplePage("Not found", "This proposal link isn't valid. Reach out if you think this is a mistake."), {
      status: 404,
      headers: { "Content-Type": "text/html; charset=utf-8" },
    });
  }

  if (prospect.status === "archived" || prospect.status === "ghosted") {
    return new Response(simplePage("This proposal is closed", "Get in touch if you'd like to revisit your custom agent setup."), {
      status: 410,
      headers: { "Content-Type": "text/html; charset=utf-8" },
    });
  }

  if (!prospect.presentationHtml) {
    const first = (prospect.contactName ?? "").trim().split(/\s+/)[0] || "there";
    return new Response(
      simplePage(
        "Your proposal is being prepared",
        `Hey ${first} — Atlas is still working on your custom agent proposal. This page will update as soon as it's ready. Usually within 30 minutes of your submission.`
      ),
      { headers: { "Content-Type": "text/html; charset=utf-8" } }
    );
  }

  return new Response(prospect.presentationHtml, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      // Don't cache — each visit reflects the latest Atlas-generated state in
      // case the prospect requested changes and Atlas regenerated.
      "Cache-Control": "no-store",
    },
  });
}

function simplePage(title: string, body: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)} · Ambitt Agents</title><style>body{font-family:'Inter',system-ui,-apple-system,sans-serif;background:#fafaf8;color:#171717;margin:0;display:flex;align-items:center;justify-content:center;min-height:100vh;padding:32px}main{max-width:520px;text-align:center}h1{font-size:28px;font-weight:700;letter-spacing:-0.5px;margin:0 0 16px}p{font-size:15px;color:#404040;line-height:1.65;margin:0 0 12px}a{color:#00b3b3;text-decoration:none;font-weight:500}a:hover{text-decoration:underline}</style></head><body><main><h1>${escapeHtml(title)}</h1><p>${escapeHtml(body)}</p><p><a href="mailto:team@ambitt.agency">team@ambitt.agency</a></p></main></body></html>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
